<?php
/**
 *
 * @package    Material Dashboard Yii2
 * @author     CodersEden <hello@coderseden.com>
 * @link       https://www.coderseden.com
 * @copyright  2020 Material Dashboard Yii2 (https://www.coderseden.com)
 * @license    MIT - https://www.coderseden.com
 * @since      1.0
 */
namespace app\controllers;
use app\models\Workers;
use Yii;



/**
 * Class TablesController
 * @package app\controllers
 */
class TablesController extends \yii\web\Controller
{
	/**
	 * @param \yii\base\Action $action
	 *
	 * @return bool|void
	 * @throws \yii\web\BadRequestHttpException
	 */
	public function beforeAction( $action )
	{
		if ( \Yii::$app->getUser()->isGuest ) {
			return \Yii::$app->getResponse()->redirect( \yii\helpers\Url::to(['/']) )->send();
		}
		return parent::beforeAction( $action ); // TODO: Change the autogenerated stub
	}

	/**
	 * @return string
	 */
    public function actionIndex()
    {
        $workList = Workers::Find()->all();
        $model = new Workers();
        if($model->load(Yii::$app->request->post()) ){
            print_r($model);
//            return $this->render('index', ['workList' => $workList]);
        } else {
            return $this->render('index', ['workList' => $workList, 'model' => $model]);
        }
    }

//    public function actionWorker()
//    {
//        $workList = Workers::Find()->all();
//        print_r($workList);
//        die;
//
//    }
}
