<?php
/**
 *
 * @package    Material Dashboard Yii2
 * @author     CodersEden <hello@coderseden.com>
 * @link       https://www.coderseden.com
 * @copyright  2020 Material Dashboard Yii2 (https://www.coderseden.com)
 * @license    MIT - https://www.coderseden.com
 * @since      1.0
 */
namespace app\controllers;
use app\models\Workers;
use app\models\Time_list;
use app\models\Clm_list_time;
use app\models\Time_model;
use Yii;



/**
 * Class TablesController
 * @package app\controllers
 */
class TablesController extends \yii\web\Controller
{
	/**
	 * @param \yii\base\Action $action
	 *
	 * @return bool|void
	 * @throws \yii\web\BadRequestHttpException
	 */
	public function beforeAction( $action )
	{
		if ( \Yii::$app->getUser()->isGuest ) {
			return \Yii::$app->getResponse()->redirect( \yii\helpers\Url::to(['/']) )->send();
		}
		return parent::beforeAction( $action ); // TODO: Change the autogenerated stub
	}

	/**
	 * @return string
	 */
    public function actionIndex()
    {
        $workList = Workers::Find()->all();

        return $this->render('index',['workList'=>$workList]);
    }

    public function actionUpdate()
    {
        $id = Yii::$app->request->get('id');
        $time = (int)Yii::$app->request->get('time');
        $time = !$time ? null : $time;
        $idworker = Workers::findOne($id);
        if(empty($idworker)) return false;
        $session = Yii::$app->session;
        $session->open();
        $list = new Time_list();
        $list->addToList($idworker, $time);
//            debug($session['Time_list']);
//        debug($session['Time_list.week_time']);
        $this->layout = false;
        return $this->render('time-modal',compact('session'));

    }

    public function actionClear(){
        $session = Yii::$app->session;
        $session->open();
        $session->remove('Time_list');
        $this->layout = false;
        return $this->render('time-modal',compact('session'));
    }

    public function actionDelItem(){
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $list = new Time_list();
        $list->recalc($id);
        $this->layout = false;
        return $this->render('time-modal',compact('session'));
    }

    public function actionShow(){
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('time-modal',compact('session'));
    }

    public function actionTime(){
        $id = Yii::$app->request->get('id');
        $time = Yii::$app->request->get('time');
        $session = Yii::$app->session;
        $session->open();
        $list = new Time_list();
        $list->addtime($id,$time);
        $this->layout = false;
        return $this->render('time-modal',compact('session'));
    }

    public function actionSafe(){
//        $this->layout=false;
        $session =Yii::$app->session;
        $session->open();
        $time = new Time_model();

        if ($time->load(Yii::$app->request->post()) && $time->validate()) {
            $this->saveWorkerTime($session['Time_list'],$time->data);
            $session->remove('Time_list');
            return $this->redirect(['tables/index']);
        }

        return $this->render('safe', compact('time'));
    }

    protected function saveWorkerTime($items, $data){
        foreach ($items as $id => $item) {
            $worker = new Clm_list_time();
            $worker->id_worker = $item['id'];
            $worker->data = $data;
            $worker->name = $item['name'];
            $worker->last_name = $item['last_name'];
            $worker->day_time = $item['week_time'];
            $worker->save();
        }

    }

}
