<?php
/**
 *
 * @package    Material Dashboard Yii2
 * @author     CodersEden <hello@coderseden.com>
 * @link       https://www.coderseden.com
 * @copyright  2020 Material Dashboard Yii2 (https://www.coderseden.com)
 * @license    MIT - https://www.coderseden.com
 * @since      1.0
 */
namespace app\controllers;
use app\models\Workers;
use app\models\Time_list;
use Yii;



/**
 * Class TablesController
 * @package app\controllers
 */
class TablesController extends \yii\web\Controller
{
	/**
	 * @param \yii\base\Action $action
	 *
	 * @return bool|void
	 * @throws \yii\web\BadRequestHttpException
	 */
	public function beforeAction( $action )
	{
		if ( \Yii::$app->getUser()->isGuest ) {
			return \Yii::$app->getResponse()->redirect( \yii\helpers\Url::to(['/']) )->send();
		}
		return parent::beforeAction( $action ); // TODO: Change the autogenerated stub
	}

	/**
	 * @return string
	 */
    public function actionIndex()
    {
        $workList = Workers::Find()->all();

        return $this->render('index',['workList'=>$workList]);
    }

    public function actionUpdate()
    {
        $id = Yii::$app->request->get('id');
        $time = (int)Yii::$app->request->get('time');
        $time = !$time ? 1 : $time;
        $idworker = Workers::findOne($id);
        if(empty($idworker)) return false;
        $session = Yii::$app->session;
        $session->open();
        $list = new Time_list();
        $list->addToList($idworker, $time);
            debug($session['Time_list']);
        debug($session['Time_list.week_time']);

    }

}
