<?php
/**
 *
 * @package    Material Dashboard Yii2
 * @author     CodersEden <hello@coderseden.com>
 * @link       https://www.coderseden.com
 * @copyright  2020 Material Dashboard Yii2 (https://www.coderseden.com)
 * @license    MIT - https://www.coderseden.com
 * @since      1.0
 */
namespace app\controllers;
use app\models;
use app\models\Orders;
use app\models\Orders_contact;
use app\models\Orders_count;
use app\models\Orders_details;
use app\models\Workers;
use app\models\OrdersSearch;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use Yii;

/**
 * Class TypographyController
 * @package app\controllers
 */
class TypographyController extends \yii\web\Controller
{
	/**
	 * @param \yii\base\Action $action
	 *
	 * @return bool|void
	 * @throws \yii\web\BadRequestHttpException
	 */
	public function beforeAction( $action )
	{
		if ( \Yii::$app->getUser()->isGuest ) {
			return \Yii::$app->getResponse()->redirect( \yii\helpers\Url::to(['/']) )->send();
		}
		return parent::beforeAction( $action ); // TODO: Change the autogenerated stub
	}

	/**
	 * @return string
	 */
    public function actionIndex()
    {
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->get());
        $dataProvider->pagination->pageSize=10;
        return $this->render('index',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        $id = Yii::$app->request->get('id');
//        $model = $this->findModel($id);
        $model = Orders::findOne($id);
        $modelcount = Orders_count::findOne(['id_orders'=>$id]);
        $modelcontact = Orders_contact::findOne(['id_orders'=>$id]);
        $modeldetails = Orders_details::findOne(['id_orders'=>$id]);

//        \Yii::$app->view->title = \Yii::t('app', 'Orders {userName}', ['userName'=>$model->fullName]);

        return $this->render('view', [
                'model' => $model,
                'modelcount' => $modelcount,
                'modelcontact' => $modelcontact,
                'modeldetails' => $modeldetails,
        ]);
    }

    public function actionCreate()
    {
        $model = new Orders();
        $modelcount = new Orders_count();
        $modelcontact = new Orders_contact();
        $modeldetails = new Orders_details();

        \Yii::$app->view->title = \Yii::t('app', 'Создать Ордер');

        if ($model->load(\Yii::$app->getRequest()->post()) && $model->save()) {
            $modelcount->id_orders = $model->id;
            $modelcontact->id_orders = $model->id;
            $modeldetails->id_orders = $model->id;

                if($modelcount->load(\Yii::$app->getRequest()->post()) && $modelcount->save())
                if($modelcontact->load(\Yii::$app->getRequest()->post()) && $modelcontact->save())
                if($modeldetails->load(\Yii::$app->getRequest()->post()) && $modeldetails->save())  

            return $this->redirect(['index']);
        } else {
            return $this->render('form', [
                'action'=> 'create',
                'model' => $model,
                'modelcount' => $modelcount,
                'modelcontact' => $modelcontact,
                'modeldetails' => $modeldetails,
            ]);
        }
    }





    protected function findModel($id)
    {
        if (($model = Orders::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }




}
